### ISSUE TITLE
For forFunderId property of FundingStatus

### ISSUE THREAD

**Issue by ghost** [commonapproach/SFF#5]
Described as forFunderId: _Links to an instance of Organization if there is a public URI  for the funder Organization_ and constrained to ```cids:Organization```. Shouldn't this be called ```forOrganization``` to be in line with the rest of the ontology?

**Comment by mrgarth** [comment]
correct, this should be forOrganization

**Comment by mrgarth** [comment]
Closed with correction made—forFunderId replaced with forOrganization

**Comment by mrgarth** [comment]
Closed with correction made—forFunderId replaced with forOrganization
